[project]
name = "api"
version = "0.1.0"
description = "This folder is for backend Fast-api"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "google-genai>=2.16.0",
    "groq>=1.6.0",
    "openai>=2.52.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "uvicorn>=0.52.1",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
shared = {workspace = true}

[tool.hatch.build.target.wheel]
packages = ["src/api"]

[tool.hatch.build.target.sdist]
include=[
    "src/",
    "tests/",
    "README.md",
]